### ISSUE TITLE
Nonresponsive RDP

### ISSUE THREAD

**Issue by init5-SF** [Pennyw0rth/NetExec#655]
**Describe the bug**
Using RDP protocol doesn't work, it simply freezes and stays that way, no error messages or anything

**To Reproduce**
Command: `netexec rdp 10.129.229.244 -u 'helen' -p RedRiot88 --debug`
Resulted in:
```
[23:44:55] DEBUG    NXC VERSION: 1.4.0 - SmoothOperator - 9668cbce - 7                                                                                                               cli.py:28
           DEBUG    PYTHON VERSION: 3.13.2 (main, Mar 13 2025, 14:29:07) [GCC 14.2.0]                                                                                            netexec.py:81
           DEBUG    RUNNING ON: Linux Release: 6.12.20-amd64                                                                                                                     netexec.py:82
           DEBUG    Passed args: Namespace(version=False, threads=256, timeout=None, jitter=None, verbose=False, debug=True, no_progress=False, log=None, force_ipv6=False,      netexec.py:83
                    dns_server=None, dns_tcp=False, dns_timeout=3, protocol='rdp', target=['10.129.229.244'], username=['helen'], password=['RedRiot88'], cred_id=[],                         
                    ignore_pw_decoding=False, no_bruteforce=False, continue_on_success=False, gfail_limit=None, ufail_limit=None, fail_limit=None, kerberos=False,                            
                    use_kcache=False, aesKey=None, kdcHost=None, pfx_cert=None, pfx_base64=None, pfx_pass=None, pem_cert=None, pem_key=None, server='https',                                  
                    server_host='0.0.0.0', server_port=None, connectback_host=None, module=None, module_options=[], list_modules=False, show_module_options=False, hash=[],                   
                    port=3389, rdp_timeout=5, nla_screenshot=False, domain=None, local_auth=False, screenshot=False, screentime=10, res='1024x768')                                           
           DEBUG    Protocol: rdp                                                                                                                                               netexec.py:137
           DEBUG    Protocol Path: /root/.local/pipx/venvs/netexec/lib/python3.13/site-packages/nxc/protocols/rdp.py                                                            netexec.py:140
           DEBUG    Protocol DB Path: /root/.local/pipx/venvs/netexec/lib/python3.13/site-packages/nxc/protocols/rdp/database.py                                                netexec.py:142
           DEBUG    symmetric using "pyCryptodomex" for "DES"                                                                                                                   __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "TDES"                                                                                                                  __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "AES"                                                                                                                   __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "RC4"                                                                                                                   __init__.py:55
           DEBUG    Protocol Object: <class 'protocol.rdp'>, type: <class 'type'>                                                                                               netexec.py:145
           DEBUG    Protocol DB Object: <class 'protocol.database'>                                                                                                             netexec.py:147
           DEBUG    DB Path: /root/.nxc/workspaces/default/rdp.db                                                                                                               netexec.py:150
           DEBUG    Using selector: EpollSelector                                                                                                                        selector_events.py:64
           DEBUG    Creating ThreadPoolExecutor                                                                                                                                  netexec.py:45
           DEBUG    Creating thread for <class 'protocol.rdp'>                                                                                                                   netexec.py:48
           INFO     Socket info: host=10.129.229.244, hostname=10.129.229.244, kerberos=False, ipv6=False, link-local ipv6=False                                             connection.py:165
           DEBUG    Kicking off proto_flow                                                                                                                                   connection.py:227
           DEBUG    Checking NLA for 10.129.229.244                                                                                                                                 rdp.py:171
           DEBUG    Using selector: EpollSelector                                                                                                                        selector_events.py:64
^C^C[00:23:28] DEBUG    Got keyboard interrupt                                                                                                                                      netexec.py:228

```

**Expected behavior**
Should show the PWNED prefix, the account does have RDP privs

**Screenshots**

![Image](https://github.com/user-attachments/assets/c19542ea-84fd-4eb4-a8bb-174a684fdded)

**NetExec info**
 - OS: Kali
 - Version of nxc: 1.4.0 - SmoothOperator - 9668cbce - 7
 - Installed from: `pipx install git+https://github.com/Pennyw0rth/NetExec`

**Comment by Marshall-Hallenbeck** [comment]
Hey, thanks for the report. Do you have any more information about the server you're trying to connect to?

**Comment by init5-SF** [comment]
Sure, it's a HTB server, I can access it normally via `xfreerdp` and `rdesktop`

```
Host Name:                 SRV01
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Server
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:   
Product ID:                00429-00521-62775-AA832
Original Install Date:     5/13/2024, 6:05:31 AM
System Boot Time:          4/24/2025, 12:43:36 PM
System Manufacturer:       VMware, Inc.
System Model:              VMware7,1
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 1 Stepping 1 AuthenticAMD ~2445 Mhz
BIOS Version:              VMware, Inc. VMW71.00V.24224532.B64.2408191458, 8/19/2024
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     4,095 MB
Available Physical Memory: 2,964 MB
Virtual Memory: Max Size:  4,799 MB
Virtual Memory: Available: 3,728 MB
Virtual Memory: In Use:    1,071 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    inlanefreight.local
Logon Server:              \\DC01
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5009472
                           [02]: KB4535680
                           [03]: KB4589208
                           [04]: KB5010427
                           [05]: KB5009642
Network Card(s):           2 NIC(s) Installed.
                           [01]: vmxnet3 Ethernet Adapter
                                 Connection Name: Ethernet0
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.129.0.1
                                 IP address(es)
                                 [01]: 10.129.229.244
                                 [02]: fe80::1d67:f4df:b695:3ea8
                                 [03]: dead:beef::1d67:f4df:b695:3ea8
                           [02]: vmxnet3 Ethernet Adapter
                                 Connection Name: Ethernet1
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.20.0.51
                                 [02]: fe80::1045:9ef3:da61:8e25
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

```

**Comment by w3soul** [comment]
I have faced this exact same behavior as well.

It doesn't happen for all Windows servers, but for some server it just hangs exactly at the same position for me:
```Using selector: Epollselector```

**Comment by NeffIsBack** [comment]
That is very weird, because it stops right before the asynchronous execution. My first guess would be that something in the rdp protocol/library is interfering with pythons async execution engine. This only happens with the RDP protocol right?

**Comment by NeffIsBack** [comment]
But that's independent from the RDP freeze right?

The freeze in SMB might be due to a recent change in the smb database which is a bit buggy with sqlalchemy. Try to remove the smb.db in the nxc folder and that should be fixed

**Comment by w3soul** [comment]
Yes, in my experience, only with RDP protocol?

Here, i have example for you, the pane on top is Server 2019, a domain joined machine (hung on Using selector). The one on the bottom is local VM running windows 10.

I can RDP into this domain joined machine with xfreerdp3, no problem.

![Image](https://github.com/user-attachments/assets/7d37e623-ec40-4145-8048-67313cb6479c)

> That is very weird, because it stops right before the asynchronous execution. My first guess would be that something in the rdp protocol/library is interfering with pythons async execution engine. This only happens with the RDP protocol right?

**Comment by w3soul** [comment]
Unfortunately yes, the One that hung for me in top pane is Altered Security CRTE lab.

**Comment by init5-SF** [comment]
> But that's independent from the RDP freeze right?
> 
> The freeze in SMB might be due to a recent change in the smb database which is a bit buggy with sqlalchemy. Try to remove the smb.db in the nxc folder and that should be fixed

You're right, deleting `smb.db` solved the smb freeze, but the RDP issue remains.
If you need any kind of information from the target server i.e. banners, registry values, etc. Let me know, happy to help!

**Comment by asareynolds** [comment]
@NeffIsBack I'm having the same RDP error. It occurs at the same step when running nxc from Windows and Linux in my environment. Windows hangs after "Checking NLA" with `Using proactor: IocpProactor`. Linux hangs after "Checking NLA" with `Using selector: EpollSelector`.

**Comment by NeffIsBack** [comment]
> [@NeffIsBack](https://github.com/NeffIsBack) I'm having the same RDP error. It occurs at the same step when running nxc from Windows and Linux in my environment. Windows hangs after "Checking NLA" with `Using proactor: IocpProactor`. Linux hangs after "Checking NLA" with `Using selector: EpollSelector`.

Which version are you on? Have you tried removing the database file?

**Comment by asareynolds** [comment]
> Which version are you on? Have you tried removing the database file?

v1.4.0, removing and restarting with a new database resulted in the same error. This is a similar situation to w3soul's error where the target machine is part of a private lab.

**Comment by NeffIsBack** [comment]
> > Which version are you on? Have you tried removing the database file?
> 
> v1.4.0, removing and restarting with a new database resulted in the same error. This is a similar situation to w3soul's error where the target machine is part of a private lab.

I meant the exact version. Try it with the latest commits from github. There was an issue with the database near the release. When you upgraded the version try removing the smb.db file once so you have a fresh database.

**Comment by asareynolds** [comment]
> > > Which version are you on? Have you tried removing the database file?
> > 
> > v1.4.0, removing and restarting with a new database resulted in the same error. This is a similar situation to w3soul's error where the target machine is part of a private lab.
> 
> I meant the exact version. Try it with the latest commits from github. There was an issue with the database near the release. When you upgraded the version try removing the smb.db file once so you have a fresh database.

Ok, I don't have access to the specific lab right now but I will in a few weeks so I'll check then. I haven't experienced the error on other labs so it seems situational.

**Comment by init5-SF** [comment]
Just tried using the latest commit:
```
    Version : 1.4.0
    Codename: SmoothOperator
    Commit  : a8183f88
```

I can confirm that the issue still exists

<img width="1705" height="605" alt="Image" src="https://github.com/user-attachments/assets/78d366f2-5238-49c3-bd4d-b6face07f7df" />
