### ISSUE TITLE
Windows PFX authentication not working: no such file or directory

### ISSUE THREAD

**Issue by andretorresbr** [Pennyw0rth/NetExec#656]
**Describe the bug**
I'm using latest version (1.4.0) in a Windows 10 x64 machine. I'm trying to authenticate to the domain using a PFX certificate, which works perfectly using Rubeus or Certipy.
There seems to be a problem about where nxc stores the .ccache file:

![Image](https://github.com/user-attachments/assets/36521342-06d7-4c3e-bd42-332a808f0dec)

The .nxc directory was created properly:

![Image](https://github.com/user-attachments/assets/d33f36df-48a5-40be-8fc9-b4dd7b94dbb9)

The strange thing that I noticed is the path shown in error message: `'C-\\Users\\andre.torres/.nxc...`
Maybe this `C-` is the reason for the error.

I also tried using .pem certificates, with same error.

**To Reproduce**
Command: `.\nxc.exe smb corp-dc.corp.local -u breaktheglass_da --pfx-cert c:\Tools\esc1.pfx --pfx-pass "certpass"`
Resulted in:
```
.\nxc.exe smb corp-dc.corp.local -u breaktheglass_da --pfx-cert c:\Tools\esc1.pfx --pfx-pass "certpass"

[23:31:33] ERROR    Exception while calling proto_flow() on target corp-dc.corp.local: [Errno 2] No such file or directory:                 connection.py:176
                    'C-\\Users\\andre.torres/.nxc/logs/CORP-DC_10.0.0.10_2025-04-23_233133-breaktheglass_da.ccache'
                    ╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
                    │ in __init__:168                                                                                                     │
                    │                                                                                                                     │
                    │ in proto_flow:235                                                                                                   │
                    │                                                                                                                     │
                    │ in login:559                                                                                                        │
                    │                                                                                                                     │
                    │ in pfx_auth:522                                                                                                     │
                    │                                                                                                                     │
                    │ in to_file:828                                                                                                      │
                    ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    FileNotFoundError: [Errno 2] No such file or directory:
                    'C-\\Users\\andre.torres/.nxc/logs/CORP-DC_10.0.0.10_2025-04-23_233133-breaktheglass_da.ccache'
```

**Expected behavior**
PFX authentication working properly.

**Screenshots**
Shown before.

**NetExec info**
 - OS: Windows 10 x64 22H2
 - Version of nxc: 1.4.0 (latest available)
 - Installed from: github Windows release

**Comment by andretorresbr** [comment]
I also noticed that other commands are returning the same FileNotFound error in version 1.4.0:

.\nxc.exe smb srv-01.corp.local -u andre.torres_a -p "pass" --sam

![Image](https://github.com/user-attachments/assets/ab2ead97-0408-4a5f-acb5-e419703b04a8)

When downgrading to previous version 1.3.0, the same command works flawless:

![Image](https://github.com/user-attachments/assets/2b811ee8-8420-41fb-bb91-be29447e2d79)

**Comment by NeffIsBack** [comment]
At least `--sam` and `--lsa` should have been fixed a couple of days ago:

https://github.com/Pennyw0rth/NetExec/pull/650

Can you rebuild your binary and try again? Or what is the exact version?

**Comment by andretorresbr** [comment]
I was using the pre compiled version available in releases (1.4.0 released 2 weeks ago).
I'll try to build it from the latest version.

**Comment by andretorresbr** [comment]
@NeffIsBack I have recompiled with latest version and sam/lsa is working indeed.

However, PFX authentication is presenting the same problem as reported:

![Image](https://github.com/user-attachments/assets/f832399e-79ef-42d9-8ce1-93fb622b1da4)

**Comment by NeffIsBack** [comment]
@andretorresbr that is great to hear, can you checkout, rebuild and try https://github.com/Pennyw0rth/NetExec/pull/665? That should hopefully fix the issue

**Comment by andretorresbr** [comment]
Sorry, the problem persists with the exact same error message.

![Image](https://github.com/user-attachments/assets/0d88513c-5b54-4fed-abfd-6151f3e26295)

I double checked that file pfx.py had the line 506 changed.

![Image](https://github.com/user-attachments/assets/143cdefd-fbdf-4a97-b4cc-03b303727462)

![Image](https://github.com/user-attachments/assets/a272435c-a2da-425a-8f31-9d9ce8ff0ed2)

**Comment by NeffIsBack** [comment]
> Maybe this `C-` is the reason for the error.

@andretorresbr you were right with your initial guess, that was at least part of the problem, fixing it now in #665

**Comment by andretorresbr** [comment]
This corrected the "File not found" problem. Thanks @NeffIsBack for your great help!

However, the new code freezes the PFX authentication:

![Image](https://github.com/user-attachments/assets/d383d800-0399-4396-8d05-505f9b8185de)

Running in debug mode, it freezes on smb.py:664

![Image](https://github.com/user-attachments/assets/0b39597c-304a-4260-a5bd-ceae24f5e9ba)

[debug_output.txt](https://github.com/user-attachments/files/19929997/debug_output.txt)

I also tried using a different .pfx (a machine one) without password, and this freezes in a previous step (Checking if user is admin on 10.0.0.10 - smb.py:649):

![Image](https://github.com/user-attachments/assets/93a9ad80-196f-4701-a5e7-0bed8dad649c)

**Comment by NeffIsBack** [comment]
Had exactly the same issue. Try to remove your smb db at ~/.nxc/workspaces/default/smb.db

**Comment by andretorresbr** [comment]
Again, you are right, @NeffIsBack 

After removing smb.db, it works perfectly. Cheers!

![Image](https://github.com/user-attachments/assets/b72eaafc-efb8-40e0-8c09-217047b161b0)
